<?php
/**
 * Config file
 */
//English language constants
global $eng_lang;
$eng_lang['login_form_legend']='Login From';
$eng_lang['sign_in']='Sign In';
$eng_lang['email']='Email';
$eng_lang['email_placeholder']='Please enter your email...';
$eng_lang['pwd']='Password';
$eng_lang['login_btn']='Login';
$eng_lang['si_form_legend']='Sign In form';
$eng_lang['first']='First name';
$eng_lang['first_p']='Please enter your first name...';
$eng_lang['last']='Last name';
$eng_lang['last_p']='Please enter your last name...';
$eng_lang['phone']='Phone';
$eng_lang['phone_p']='Please enter your phone number...';
$eng_lang['av']='Avatar';
$eng_lang['birth']='Birth date';
$eng_lang['birth_p']='Please enter your birth date...';
$eng_lang['marital']='Marital status';
$eng_lang['m_option']='Married';
$eng_lang['u_option']='Unmarried';
$eng_lang['ed']='Education';
$eng_lang['ed_p']='Please enter your education...';
$eng_lang['ex']='Experience';
$eng_lang['ex_p']='Please enter your experience...';
$eng_lang['ad']='Additional info';
$eng_lang['ad_p']='Please enter your additional info if you have...';
$eng_lang['log_out']='Log out';
$eng_lang['profile']='Profile';
$eng_lang['first_tt']='You can enter your first name or your nikcname.';
$eng_lang['last_tt']='You must enter your last name.';
$eng_lang['phone_tt']='For communicate you must enter your phone.';
$eng_lang['newlogin_tt']='Enter your working email.';
$eng_lang['pwd_tt']='Enter password (more than 5 symbols must be)';
$eng_lang['av_tt']='You can upload your photo.';
$eng_lang['birth_tt']='Enter please your birth date.';
$eng_lang['marital_tt']='Enter please your marital status.';
$eng_lang['ed_tt']='Enter your education.';
$eng_lang['ex_tt']='Enter your experience.';
$eng_lang['ad_tt']='Enter additional information.';
$eng_lang['about']='About me';
$eng_lang['switch_lang']='Switch language to russian';
$eng_lang['test_task']='Test task (User login)';
$eng_lang['phone_error']='The phone input can be null!!!';
$eng_lang['email_error']='The email input can be null!!!';

//Russian language constants
global $ru_lang;
$ru_lang['login_form_legend']='Форма входа';
$ru_lang['sign_in']='Регистрация';
$ru_lang['email']='Email';
$ru_lang['email_placeholder']='Введите пожалуйста Ваш email...';
$ru_lang['pwd']='Пароль';
$ru_lang['login_btn']='Вход';
$ru_lang['si_form_legend']='Форма регистрации';
$ru_lang['first']='Имя';
$ru_lang['first_p']='Введите пожалуйста Ваше имя...';
$ru_lang['last']='Фамилия';
$ru_lang['last_p']='Введите пожалуйста Вашу фамилию...';
$ru_lang['phone']='Телефон';
$ru_lang['phone_p']='Введите пожалуйста Ваш телефон...';
$ru_lang['av']='Ваше фото';
$ru_lang['birth']='Дата рождения';
$ru_lang['birth_p']='Введите пожалуйста Вашу дату рождения...';
$ru_lang['marital']='Семейный статус';
$ru_lang['m_option']='Женат';
$ru_lang['u_option']='Не женат';
$ru_lang['ed']='Образование';
$ru_lang['ed_p']='Ваше образование...';
$ru_lang['ex']='Опыт работы';
$ru_lang['ex_p']='Ваш опыт работы';
$ru_lang['ad']='Дополнительная информация';
$ru_lang['ad_p']='Ваша дополнительная информация...';
$ru_lang['log_out']='Выход';
$ru_lang['profile']='Профиль';
$ru_lang['first_tt']='Вы можете ввести свое имя или nikcname.';
$ru_lang['last_tt']='Необходимо ввести фамилию.';
$ru_lang['phone_tt']='Введите номер Вашего телефона.';
$ru_lang['newlogin_tt']='Введите email (email должен быть рабочим).';
$ru_lang['pwd_tt']='Введите пароль (пароль должен быть больше 6 символов)';
$ru_lang['av_tt']='Вы можете загрузить свое фото.';
$ru_lang['birth_tt']='Введите пожалуйста дату рождения.';
$ru_lang['marital_tt']='Выберите статус Вашего семейного положения.';
$ru_lang['ed_tt']='Введите образование.';
$ru_lang['ex_tt']='Введите опыт работы.';
$ru_lang['ad_tt']='Введите дополнительную информацию.';
$ru_lang['about']='Обо мне';
$ru_lang['switch_lang']='Переключиться на английский язык';
$ru_lang['test_task']='Тестовое задание (Аутентификация пользователя)';
$ru_lang['phone_error']='Телефон не может быть пусты!!!';
$ru_lang['email_error']='Email не может быть пустым!!!';
